apiVersion: v1
kind: Service
metadata:
  name: caddy-service
  labels:
    app: caddy
spec:
  selector:
    app: caddy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
