apiVersion: apps/v1
kind: Deployment
metadata:
  name: caddy-webserver
  labels:
    app: caddy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: caddy
  template:
    metadata:
      labels:
        app: caddy
    spec:
      containers:
        - name: caddy
          image: caddy:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: caddy-data
              mountPath: /usr/share/caddy
      volumes:
        - name: caddy-data
          emptyDir: {}
