apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-config
data:
  Caddyfile: |
    {
        email your-email@example.com
        # Optional: enables automatic HTTPS for Caddy
        # experimental_http3
    }

    :80 {
        respond "Hello, Caddy is working!" 200
    }
